// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcsxucuqlebddxtlnvim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjc3h1Y3VxbGViZGR4dGxudmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0MzQyMDUsImV4cCI6MjA5MDAxMDIwNX0.6Q6keVsKPExXJrtD6bUow52DtMYLr2-a838UAxGFljU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});